from pathlib import Path

ROOTDIR = Path(__file__).parent
FILESDIR = ROOTDIR / 'files'
LOGOPATH = FILESDIR / 'logo.png'


# colors
PRIMARY_COLOR = '#1e81b0'
DARKER_COLOR = '#16658a'
DARKEST_COLOR = '#115270'


BIGGER_FONT = 40
MEDIUM_FONT = 24
SMALL_FONT = 16

DEFAULT_MARGIN = 15

MINIMUM_WIDTH = 200
